apiVersion: config.istio.io/v1alpha2
kind: V1alpha2RouteRule
metadata:
  name: ratings-default
spec:
  hosts:
    - ratings
  http:
    - match:
      - headers:
          cookie:
            regex: "^(.*?;)?(user=jason)(;.*)?$"
      fault:
        delay:
          percent: 100
          fixedDelay: 7s
