apiVersion: config.istio.io/v1alpha2
kind: V1alpha2RouteRule
metadata:
  name: reviews-default
spec:
  hosts:
    - reviews
  http:
    - match:
      - headers:
          cookie:
            regex: "^(.*?;)?(user=jason)(;.*)?$"
      route:
      - destination:
          name: reviews
          subset: v2
        weight: 100
    - route:
      - destination:
          name: reviews
          subset: v1
        weight: 100
