apiVersion: config.istio.io/v1alpha2
kind: V1alpha2RouteRule
metadata:
  name: ratings-default
spec:
  hosts:
  - ratings
  http:
  - route:
    - destination:
        name: ratings
        subset: v2-mysql
      weight: 100
---
apiVersion: config.istio.io/v1alpha2
kind: V1alpha2RouteRule
metadata:
  name: reviews-default
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        name: reviews
        subset: v3
      weight: 100
