apiVersion: config.istio.io/v1alpha2
kind: V1alpha2RouteRule
metadata:
  name: reviews-default
spec:
  hosts:
    - reviews
  http:
    - route:
      - destination:
          name: reviews
          subset: v1
        weight: 50
      - destination:
          name: reviews
          subset: v3
        weight: 50
