apiVersion: config.istio.io/v1alpha2
kind: V1alpha2RouteRule
metadata:
  name: details-default
spec:
  hosts:
    - details
  http:
    - route:
      - destination:
          name: details
          subset: v2
        weight: 100
